var COMMANDS = [
  { command: 'g',
    url: 'https://www.google.com',
    search: '/search?q=',
    'help-command': 'g (;&ltquery&gt)',
    'help-desc': 'Google',
    'options-text': 'Search Google'
  },
  { command: 'dg',
    url: 'https://duckduckgo.com',
    search: '/?q=',
    'help-command': 'dg (;&ltquery&lt)',
    'help-desc': 'DuckDuckGo',
    'options-text': 'Search DuckDuckGo'
  },
  { command: 'r',
    url: 'https://www.reddit.com',
    search: '/r/',
    'help-command': 'r (;&ltsubreddit&lt)',
    'help-desc': 'Reddit',
    'options-text': 'Go to subreddit'
  },
  { command: 'y',
    url: 'https://www.youtube.com',
    search: '/results?search_query=',
    'help-command': 'y (;&ltquery&lt)',
    'help-desc': 'YouTube',
    'options-text': 'Search YouTube'
  },
  { command: 'a',
    url: 'https://smile.amazon.com',
    search: '/s/?field-keywords=',
    'help-command': 'a (;&ltquery&lt)',
    'help-desc': 'Amazon',
    'options-text': 'Search Amazon'
  },
  { command: 'w',
    url: 'https://www.wikipedia.org',
    search: '/w/index.php?title=Special:Search&search=',
    'help-command': 'w (;&ltquery&lt)',
    'help-desc': 'Wikipedia',
    'options-text': 'Search Wikipedia'
  },
  { command: 'wa',
    url: 'https://www.wolframalpha.com',
    search: '/input/?i=',
    'help-command': 'wa (;&ltquery&lt)',
    'help-desc': 'Wolfram Alpha',
    'options-text': 'Search Wolfram Alpha'
  },
  { command: 'imdb',
    url: 'https://www.imdb.com',
    search: '/find?s=all&q=',
    'help-command': 'imdb (;&ltquery&lt)',
    'help-desc': 'Internet Movie Database',
    'options-text': 'Search Internet Movie Database'
  },
  { command: 'n',
    url: 'https://www.netflix.com',
    search: '/search?q=',
    'help-command': 'n (;&ltquery&lt)',
    'help-desc': 'Netflix',
    'options-text': 'Search Netflix'
  },
  { command: 'i',
    url: 'https://inbox.google.com',
    search: '/search/',
    'help-command': 'i (;&ltquery&lt)',
    'help-desc': 'Google Inbox',
    'options-text': 'Search Google Inbox'
  },
  { command: 'img',
    url: 'https://www.google.com',
    search: '/search?tbm=isch&q=',
    'help-command': 'img (;&ltquery&lt)',
    'help-desc': 'Google Images',
    'options-text': 'Search Google Images'
  },
  { command: 'k',
    url: 'https://keep.google.com',
    search: '/#search/text=',
    'help-command': 'k (;&ltquery&lt)',
    'help-desc': 'Google Keep',
    'options-text': 'Search Google Keep'
  }
];
